# Generated by Django 5.2.1 on 2025-05-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_alter_entry_image_alter_profile_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date']},
        ),
    ]
